"""add canonical_document_id and dedup_strategy

Revision ID: 687b4ba84ac7
Revises: b317633fa436
Create Date: 2026-05-11 22:21:53.001801

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "687b4ba84ac7"
down_revision: str | Sequence[str] | None = "b317633fa436"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
