"""add file_hash to documents

Revision ID: 74a0da12ed52
Revises: b684d8d4c2c1
Create Date: 2026-05-11 20:26:10.256153

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74a0da12ed52"
down_revision: str | Sequence[str] | None = "b684d8d4c2c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_documents_file_hash"), "documents", ["file_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_file_hash"), table_name="documents")
    op.drop_column("documents", "file_hash")
    # ### end Alembic commands ###
