"""add canonical_document_id to documents

Revision ID: b317633fa436
Revises: 74a0da12ed52
Create Date: 2026-05-11 22:19:19.924934

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b317633fa436"
down_revision: str | Sequence[str] | None = "74a0da12ed52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("canonical_document_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("dedup_strategy", sa.String(length=20), nullable=True)
    )
    op.create_foreign_key(
        None,
        "documents",
        "documents",
        ["canonical_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "dedup_strategy")
    op.drop_column("documents", "canonical_document_id")
    # ### end Alembic commands ###
