"""add_refresh_token_to_user

Revision ID: e2930b41b777
Revises: 42b37ce325bd
Create Date: 2026-05-06 18:19:46.686039

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2930b41b777"
down_revision: str | Sequence[str] | None = "42b37ce325bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_refresh_token", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_refresh_token")
    # ### end Alembic commands ###
